version: '3.8'

services:
  deno:
    container_name: fizz-buzz-deno
    image: denoland/deno:1.24
    tty: true
    volumes:
      - ./app:/app
      - ./deps:/deno-dir/deps
    command: "tail -f /dev/null"
    working_dir: /app